apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: 0402c9ec-a21b-4b53-ab38-5442cc70600b
    credentials-file: /etc/cloudflared/creds/credentials.json

    loglevel: info

    ingress:
      # API subdomain
      - hostname: api.mega-pdf.com
        service: http://megapdf-api.megapdf-api.svc.cluster.local:8080
      
      # Main domain
      - hostname: mega-pdf.com
        service: http://megapdf.megapdf.svc.cluster.local:3000

      # Add any other specific subdomains you need
      - hostname: db.mega-pdf.com
        service: http://phpmyadmin-service.megapdf-api.svc.cluster.local:80
      
      
      # www subdomain
      - hostname: www.mega-pdf.com
        service: http://megapdf.megapdf.svc.cluster.local:3000
      
      # Add any other specific subdomains you need
      # - hostname: blog.mega-pdf.com
      #   service: http://megapdf.megapdf.svc.cluster.local:3000
      

      # Catch-all rule for anything else
      - service: http_status:404
