apiVersion: v1
kind: Secret
metadata:
  name: scanpro-db-secret
  namespace: scanpro
type: Opaque
data:
  POSTGRES_DB: c2NhbnBybw== # "scanpro" in base64
  POSTGRES_USER: c2NhbnBybw== # "scanpro" in base64
  POSTGRES_PASSWORD: QXFzd2RlITEyMw== # "Aqswde!123" in base64
  POSTGRES_HOST: cG9zdGdyZXNxbA== # "postgresql" in base64
  POSTGRES_PORT: NTQzMg== # "5432" in base64
