apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migration
  namespace: scanpro
spec:
  template:
    spec:
      containers:
      - name: prisma-migrate
        image: cakr/scanpro-frontend:latest
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          value: "postgresql://scanprouser:Ingatallah14@localhost:5432/scanprodb?schema=public"
      restartPolicy: Never
  backoffLimit: 4