apiVersion: batch/v1
kind: Job
metadata:
  name: scanpro-db-migrate
  namespace: scanpro
spec:
  template:
    spec:
      containers:
        - name: prisma-migrate
          image: cakr/scanpro-frontend:latest
          command:
            ["sh", "-c", "npx prisma generate && npx prisma migrate deploy"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: scanpro-external-db-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: scanpro-external-db-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: scanpro-external-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scanpro-external-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: scanpro-external-db-secret
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?schema=public"
      restartPolicy: Never
  backoffLimit: 3
