apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanpro-uploads-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scanpro-storage
  hostPath:
    path: /mnt/data/scanpro/uploads
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanpro-public-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scanpro-storage
  hostPath:
    path: /mnt/data/scanpro/public
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanpro-temp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: scanpro-storage
  hostPath:
    path: /mnt/data/scanpro/temp