apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-uploads-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: scanpro-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-conversions-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: scanpro-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-compressions-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: scanpro-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-temp-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: scanpro-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-postgres-data-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: scanpro-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-redis-data-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: scanpro-storage
