apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanpro
  namespace: scanpro
  labels:
    app: scanpro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scanpro
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: scanpro
    spec:
      containers:
        - name: scanpro
          image: cakr/scanpro-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            # Core application environment
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NODE_ENV
            - name: NEXT_PUBLIC_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_APP_URL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: NEXTAUTH_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: OPENAI_API_KEY
            # SMTP configuration
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: SMTP_PASSWORD
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: SMTP_SECURE
            - name: EMAIL_FROM
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: EMAIL_FROM
            # Google Analytics and Tag Manager
            - name: NEXT_PUBLIC_GA_MEASUREMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_GA_MEASUREMENT_ID
            - name: NEXT_PUBLIC_GTM_ID
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_GTM_ID
            # Google OAuth
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: GOOGLE_CLIENT_SECRET
            # PayPal configuration
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: PAYPAL_CLIENT_ID
            - name: PAYPAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: PAYPAL_CLIENT_SECRET
            - name: PAYPAL_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: PAYPAL_WEBHOOK_SECRET
            - name: PAYPAL_WEBHOOK_ID
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: PAYPAL_WEBHOOK_ID
            - name: PAYPAL_PLAN_BASIC
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: PAYPAL_PLAN_BASIC
            - name: PAYPAL_PLAN_PRO
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: PAYPAL_PLAN_PRO
            - name: PAYPAL_PLAN_ENTERPRISE
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: PAYPAL_PLAN_ENTERPRISE
            # Upstash Redis
            - name: UPSTASH_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: UPSTASH_REDIS_URL
            - name: UPSTASH_REDIS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: UPSTASH_REDIS_TOKEN
            # Firebase configuration
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: scanpro-secret
                  key: NEXT_PUBLIC_FIREBASE_API_KEY
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
            - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_FIREBASE_APP_ID
            - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
            - name: public-volume
              mountPath: /app/public
            - name: temp-volume
              mountPath: /app/temp
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: scanpro-uploads-pvc
        - name: public-volume
          persistentVolumeClaim:
            claimName: scanpro-public-pvc
        - name: temp-volume
          persistentVolumeClaim:
            claimName: scanpro-temp-pvc