apiVersion: v1
kind: Secret
metadata:
  name: scanpro-secret
  namespace: scanpro
type: Opaque
data:
  # Base64 encoded values - replace with actual secrets in production
  # echo -n "your-nextauth-secret" | base64
  # echo -n "your-openai-api-key" | base64
  # echo -n "your-paypal-client-id" | base64
  # echo -n "your-paypal-client-secret" | base64
  NEXTAUTH_SECRET: eW91ci1uZXh0YXV0aC1zZWNyZXQ=
  OPENAI_API_KEY: eW91ci1vcGVuYWktYXBpLWtleQ==
  UPSTASH_REDIS_TOKEN: eW91ci11cHN0YXNoLXJlZGlzLXRva2Vu
  SMTP_HOST: bWFpbC5leGFtcGxlLmNvbQ==
  SMTP_PORT: NTg3
  SMTP_USER: bWFpbEBleGFtcGxlLmNvbQ==
  SMTP_PASSWORD: eW91ci1zbXRwLXBhc3N3b3Jk
  EMAIL_FROM: bm9yZXBseUBzY2FucHJvLmNjCg==
  PAYPAL_CLIENT_ID: eW91ci1wYXlwYWwtY2xpZW50LWlk
  PAYPAL_CLIENT_SECRET: eW91ci1wYXlwYWwtY2xpZW50LXNlY3JldA==
  GOOGLE_CLIENT_ID: eW91ci1nb29nbGUtY2xpZW50LWlk
  GOOGLE_CLIENT_SECRET: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==
  GITHUB_CLIENT_ID: eW91ci1naXRodWItY2xpZW50LWlk
  GITHUB_CLIENT_SECRET: eW91ci1naXRodWItY2xpZW50LXNlY3JldA==
  APPLE_CLIENT_ID: eW91ci1hcHBsZS1jbGllbnQtaWQ=
  APPLE_CLIENT_SECRET: eW91ci1hcHBsZS1jbGllbnQtc2VjcmV0
