apiVersion: v1
kind: Service
metadata:
  name: scanpro
  namespace: scanpro
  labels:
    app: scanpro
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: scanpro
